[Marker]
; Marker Movement
MoveForward=I
MoveBackward=K
MoveLeft=J
MoveRight=L
MoveUp=U
MoveDown=O

; Marker Rotation
RotateYawCCW=[
RotateYawCW=]
RotatePitchUp=;
RotatePitchDown='
RotateRollLeft=.
RotateRollRight=/

; Shortcuts
TeleportToMarker=M
ResetMarkerToPlayer=H
